### PR TITLE
Fix enumeration of SMIRNOFF trefoil impropers

### LINKED ISSUE #171: Enumerate trefoil impropers
Originally posted by @SimonBoothroyd: 

> when looking at an OpenFF system created for formaldehyde I only see a single entry in the slot map while I think it should have 6 due to the trefoil enumeration - did you intend to deduplicate the enumerated indices then re-enumerate them later, or is this just a bug?

(this is a bug/missing behavior)

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
### Description

Fixes #171

### Checklist
- [X] Add tests
- [X] Lint
- [ ] Update docstrings

### CODE REVIEW

**Comment by SimonBoothroyd** [comment]
@mattwthompson any ideas why the tests are failing? I'm not familiar with LAMMPS

**Comment by mattwthompson** [comment]
Guarantee it's a bug in my writer. I probably won't get to this today, so if this is in any way blocking stuff you want to do, feel free to skip those tests.

**Comment by mattwthompson** [comment]
Thanks @SimonBoothroyd!

**Comment by SimonBoothroyd** [comment]
Great - thanks @mattwthompson !

**Pull request merged**
